version: '3.8'

services:
  mysql_8:
    container_name: mysql_9
    image: docker.io/bitnami/mysql:8.1
    ports:
      - '3399:3306'
    volumes:
      - 'mysql_data:/bitnami/mysql/data'
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=password

volumes:
  mysql_data:
    driver: local
